[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
upload_speed = 921600
upload_protocol = esptool
upload_port = /dev/ttyACM0
lib_deps =
	adafruit/Adafruit NeoPixel@^1.15.5
